"""Stub of ``grok_build_bridge.builder``."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any


def generate_code(build_spec: Any, *_args: Any, **_kwargs: Any) -> dict[str, Any]:
    name = (
        str(build_spec.get("name", "stub"))
        if isinstance(build_spec, Mapping)
        else "stub"
    )
    files: dict[str, str] = {}
    raw_files = build_spec.get("files") if isinstance(build_spec, Mapping) else None
    if isinstance(raw_files, Mapping):
        files = {str(k): str(v) for k, v in raw_files.items()}
    elif isinstance(raw_files, Sequence) and not isinstance(raw_files, (str, bytes)):
        for entry in raw_files:
            if not isinstance(entry, Mapping):
                continue
            path = entry.get("path") or entry.get("filename")
            content = entry.get("template") or entry.get("content") or ""
            if path:
                files[str(path)] = str(content)
    if not files:
        files = {f"{name}.py": f"# {name} — generated by Bridge stub\n"}
    return {"name": name, "files": files, "tokens": 0}
