"""FastAPI application factory for ``bridge.live``.

Routes are intentionally minimal — a paste-or-upload home page, a POST
endpoint that returns a passport URL, the passport page itself, the
showcase gallery, and a query-string handoff for "launch from this
tweet/topic" deep links.

Every YAML processed here is treated as untrusted input. Two
mitigations:

* The pipeline only runs phases 1 (schema validate) and 3 (static
  safety scan). No Grok calls, no deploys.
* :func:`grok_build_bridge.parser.load_yaml` uses the strict Draft
  2020-12 validator with ``additionalProperties: false`` everywhere,
  so unknown keys are rejected before any of our renderers touch them.

The application factory pattern (``create_app``) makes it trivial to
spin up isolated instances in tests and lets a deployment script
override the seeded gallery before serving traffic.
"""

from __future__ import annotations

import importlib.resources as resources
from pathlib import Path
from typing import Any, Final
from urllib.parse import urlencode

import yaml
from fastapi import FastAPI, Form, HTTPException, Request, UploadFile
from fastapi.responses import HTMLResponse, RedirectResponse, Response
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from bridge_live import store
from bridge_live.inspector import BridgeConfigError, passport_from_yaml

_HERE: Final[Path] = Path(__file__).parent
_TEMPLATES_DIR: Final[Path] = _HERE / "templates"
_STATIC_DIR: Final[Path] = _HERE / "static"

# Maximum YAML payload accepted from the browser. 256 KiB is generous
# for any realistic bridge.yaml (the bundled templates top out around
# 4 KB) and small enough that an abusive paste cannot exhaust memory.
_MAX_YAML_BYTES: Final[int] = 256 * 1024

# The ``?topic=`` deep link is rendered into the x-trend-analyzer
# template. This canned scaffold gives the user a runnable YAML
# starting point pre-filled with their topic. It's intentionally not
# the verbatim bundled template — we want the deep link to feel
# personalised ("monitor <topic>") rather than offering "the trend
# analyzer".
_TOPIC_SCAFFOLD: Final[str] = """\
version: "1.0"
name: bridge-live-{slug}
description: Hourly summary of {topic} discussion on X — generated by Bridge.
build:
  source: grok
  language: python
  entrypoint: main.py
  required_tools:
    - x_search
    - web_search
  grok_prompt: |
    Generate ONE Python 3.11 file that polls x_search for {topic},
    verifies each finding with web_search, and publishes a single
    thread every hour with primary-source citations.
deploy:
  target: x
  post_to_x: true
  schedule: "0 * * * *"
  safety_scan: true
agent:
  model: grok-4.20-0309
  reasoning_effort: medium
  personality: Neutral, factual, citation-first.
safety:
  audit_before_post: true
  max_tokens_per_run: 18000
  lucas_veto_enabled: false
"""


def create_app() -> FastAPI:
    """Build a configured FastAPI instance.

    Side effects:
      * Mounts ``/static`` at the package's ``static/`` directory.
      * Seeds the passport store from the eight bundled bridge templates
        on first launch (idempotent — re-seeding is content-addressed
        and overwrites the same SHAs).
    """
    app = FastAPI(
        title="bridge.live",
        description=(
            "Drop a bridge.yaml, get a public agent passport. Backed by grok-build-bridge."
        ),
    )
    app.mount("/static", StaticFiles(directory=_STATIC_DIR), name="static")
    templates = Jinja2Templates(directory=str(_TEMPLATES_DIR))

    _seed_showcase()

    # ---- routes ---------------------------------------------------------

    @app.get("/", response_class=HTMLResponse)
    def home(request: Request) -> Any:
        return templates.TemplateResponse(
            request,
            "home.html",
            {"prefilled": "", "topic": ""},
        )

    @app.get("/launch", response_class=HTMLResponse)
    def launch(request: Request, topic: str | None = None) -> Any:
        prefilled = _scaffold_for_topic(topic) if topic else ""
        return templates.TemplateResponse(
            request,
            "home.html",
            {"prefilled": prefilled, "topic": topic or ""},
        )

    @app.post("/p", response_class=HTMLResponse)
    async def submit(
        request: Request,
        yaml_text: str = Form(default=""),
        upload: UploadFile | None = None,
    ) -> Any:
        text = await _resolve_yaml_payload(yaml_text, upload)
        if not text:
            raise HTTPException(status_code=400, detail="Empty YAML payload.")
        if len(text.encode("utf-8")) > _MAX_YAML_BYTES:
            raise HTTPException(status_code=413, detail="YAML payload too large.")

        try:
            passport = passport_from_yaml(text)
        except BridgeConfigError as exc:
            return templates.TemplateResponse(
                request,
                "error.html",
                {"error": exc, "yaml_text": text},
                status_code=422,
            )
        store.save(passport)
        return RedirectResponse(url=f"/p/{passport.sha}", status_code=303)

    @app.get("/p/{sha}", response_class=HTMLResponse)
    def passport(request: Request, sha: str) -> Any:
        loaded = store.load(sha)
        if loaded is None:
            raise HTTPException(status_code=404, detail="Passport not found.")
        return templates.TemplateResponse(
            request,
            "passport.html",
            {"passport": loaded},
        )

    @app.get("/showcase", response_class=HTMLResponse)
    def showcase(request: Request) -> Any:
        seeded = store.list_seeded()
        return templates.TemplateResponse(
            request,
            "showcase.html",
            {"passports": seeded},
        )

    @app.get("/healthz")
    def healthz() -> Response:
        # Cheap liveness probe for hosted environments.
        return Response(content="ok", media_type="text/plain")

    return app


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _resolve_yaml_payload(yaml_text: str, upload: UploadFile | None) -> str:
    """Pick whichever side of the form submitted content; prefer paste."""
    if yaml_text and yaml_text.strip():
        return yaml_text
    if upload is not None:
        raw = await upload.read()
        try:
            return raw.decode("utf-8")
        except UnicodeDecodeError:
            return ""
    return ""


def _scaffold_for_topic(topic: str) -> str:
    """Render the canned ``?topic=`` scaffold for a launch deep link.

    The slug is sanitised because schema enforces ``[a-z0-9-]{3,64}``
    on ``name``. Falling back to ``topic`` keeps the scaffold simple
    while still validating cleanly when the user submits it.
    """
    slug = "".join(ch if ch.isalnum() else "-" for ch in topic.lower()).strip("-")[:48]
    if len(slug) < 3:
        slug = "topic"
    return _TOPIC_SCAFFOLD.format(topic=topic.strip() or "this topic", slug=slug)


def _seed_showcase() -> None:
    """Populate the passport store with the 8 bundled bridge templates.

    Each entry in ``grok_build_bridge/templates/INDEX.yaml`` becomes a
    seeded passport — clicking the "Showcase" tab in production should
    show real, runnable agents on first paint, not an empty state.
    """
    try:
        templates_root = resources.files("grok_build_bridge.templates")
        index_path = templates_root / "INDEX.yaml"
        if not index_path.is_file():
            return
        index = yaml.safe_load(index_path.read_text(encoding="utf-8")) or {}
    except (OSError, yaml.YAMLError):  # pragma: no cover — packaging bug
        return
    entries = index.get("templates") or []

    for entry in entries:
        if not isinstance(entry, dict):
            continue
        files = entry.get("files") or []
        yaml_resource: Any | None = None
        local_code_resource: Any | None = None
        for spec in files:
            if not isinstance(spec, dict):
                continue
            src = spec.get("src")
            if not isinstance(src, str):
                continue
            res = templates_root / src
            if src.endswith(".yaml") and yaml_resource is None:
                yaml_resource = res
            elif src.endswith(".py") and local_code_resource is None:
                local_code_resource = res
        if yaml_resource is None or not yaml_resource.is_file():
            continue
        yaml_text = yaml_resource.read_text(encoding="utf-8")
        extra_code: str | None = None
        if local_code_resource is not None and local_code_resource.is_file():
            extra_code = local_code_resource.read_text(encoding="utf-8")
        try:
            passport = passport_from_yaml(yaml_text, extra_code=extra_code, seeded=True)
        except BridgeConfigError:  # pragma: no cover — bundled templates always validate
            continue
        store.save(passport)


# Module-level instance so ``uvicorn bridge_live.app:app`` works without
# the user having to write ``--factory``.
app = create_app()


# Re-export for callers that prefer ``urlencode`` from the same place.
__all__ = ["app", "create_app", "urlencode"]
