"""Test fixtures and fakes.

Orchestra treats ``grok_build_bridge`` as a hard dependency. We install a
minimal stub in ``sys.modules`` before any test module imports
:mod:`grok_orchestra`, because the real Bridge package is not available in
the isolated test environment used by CI for this repository.
"""

from __future__ import annotations

import sys
import types
from pathlib import Path
from typing import Any

import yaml
from rich.console import Console


class _StubBridgeConfigError(Exception):
    """Stand-in for ``grok_build_bridge.parser.BridgeConfigError``."""


def _stub_load_yaml(path: str | Path) -> Any:
    """Stand-in for ``grok_build_bridge.parser.load_yaml``.

    Real Bridge validates against its own schema; for Orchestra tests we only
    need the raw dict. Orchestra's extension schema runs on top.
    """
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _stub_audit_x_post(*_args: Any, **_kwargs: Any) -> dict[str, Any]:
    return {"approved": True, "flagged": False}


def _stub_scan_generated_code(
    files: Any, *_args: Any, **_kwargs: Any
) -> dict[str, Any]:
    """Stand-in for ``grok_build_bridge.safety.scan_generated_code``.

    Mirrors what real Bridge returns: ``{"safe": bool, "issues": [str]}``.
    """
    del files
    return {"safe": True, "issues": []}


def _stub_generate_code(
    build_spec: Any, *_args: Any, **_kwargs: Any
) -> dict[str, Any]:
    """Stand-in for ``grok_build_bridge.builder.generate_code``.

    Returns a BridgeResult-shaped dict so the combined runtime can drive
    the Orchestra phase end-to-end without the real Bridge. When the
    spec lists ``files`` (path + template/content pairs), the stub
    threads those through so assertions about written paths line up
    with what the spec asked for. Handles both raw dicts and the
    ``MappingProxyType`` / ``tuple`` shape the Orchestra parser hands
    back. Tests can still ``unittest.mock.patch`` the symbol for full
    control.
    """
    from collections.abc import Mapping, Sequence

    name = (
        str(build_spec.get("name", "stub"))
        if isinstance(build_spec, Mapping)
        else "stub"
    )
    files: dict[str, str] = {}
    raw_files = (
        build_spec.get("files") if isinstance(build_spec, Mapping) else None
    )
    if isinstance(raw_files, Mapping):
        files = {str(k): str(v) for k, v in raw_files.items()}
    elif isinstance(raw_files, Sequence) and not isinstance(raw_files, (str, bytes)):
        for entry in raw_files:
            if not isinstance(entry, Mapping):
                continue
            path = entry.get("path") or entry.get("filename")
            content = entry.get("template") or entry.get("content") or ""
            if path:
                files[str(path)] = str(content)
    if not files:
        files = {f"{name}.py": f"# {name} — generated by Bridge stub\n"}
    return {"name": name, "files": files, "tokens": 0}


def _stub_deploy_to_target(*_args: Any, **_kwargs: Any) -> str:
    return "https://example.test/deployed"


def _stub_section(*args: Any) -> None:
    """Stand-in for ``grok_build_bridge._console.section``.

    Real Bridge ships ``section(title: str)`` and uses its module-level
    Rich console. Older Orchestra call sites pass ``(console, title)``;
    Orchestra installs a shim in ``grok_orchestra/__init__.py`` that
    normalises both shapes onto ``section(title)``. The stub mirrors
    that contract so it works whether tests bypass or exercise the
    shim.
    """
    title = args[1] if len(args) >= 2 else (args[0] if args else "")
    Console().rule(str(title), style="cyan")


class _StubChat:
    """Minimal stand-in for ``XAIClient.chat``.

    Tests typically reassign ``client.chat`` to a MagicMock, but having a
    real attribute present on construction makes the import path exercise
    the same code path it would hit in production.
    """

    def create(self, **_kwargs: Any) -> list[Any]:
        return []


class _StubXAIClient:
    """Stand-in for ``grok_build_bridge.xai_client.XAIClient``.

    Accepts any kwargs so subclasses can be instantiated in tests without
    having to mirror the real Bridge constructor. Provides a no-op
    ``single_call`` so code paths that probe for it succeed in isolation;
    tests typically replace this with a :class:`unittest.mock.MagicMock`.
    """

    def __init__(self, *_args: Any, **_kwargs: Any) -> None:
        self.chat = _StubChat()

    def single_call(self, *_args: Any, **_kwargs: Any) -> list[Any]:
        return []


class _StubRateLimitError(Exception):
    """Stand-in for ``xai_sdk.errors.RateLimitError``."""


def _stub_x_search(*_args: Any, **_kwargs: Any) -> dict[str, Any]:
    return {"type": "x_search"}


def _stub_web_search(*_args: Any, **_kwargs: Any) -> dict[str, Any]:
    return {"type": "web_search"}


def _stub_code_execution(*_args: Any, **_kwargs: Any) -> dict[str, Any]:
    return {"type": "code_execution"}


def _install_bridge_stub() -> None:
    if "grok_build_bridge" in sys.modules:
        return

    pkg = types.ModuleType("grok_build_bridge")
    parser_mod = types.ModuleType("grok_build_bridge.parser")
    safety_mod = types.ModuleType("grok_build_bridge.safety")
    deploy_mod = types.ModuleType("grok_build_bridge.deploy")
    builder_mod = types.ModuleType("grok_build_bridge.builder")
    xai_mod = types.ModuleType("grok_build_bridge.xai_client")
    console_mod = types.ModuleType("grok_build_bridge._console")

    parser_mod.load_yaml = _stub_load_yaml
    parser_mod.BridgeConfigError = _StubBridgeConfigError
    safety_mod.audit_x_post = _stub_audit_x_post
    safety_mod.scan_generated_code = _stub_scan_generated_code
    deploy_mod.deploy_to_target = _stub_deploy_to_target
    builder_mod.generate_code = _stub_generate_code
    xai_mod.XAIClient = _StubXAIClient
    console_mod.console = Console()
    console_mod.section = _stub_section

    pkg._console = console_mod  # type: ignore[attr-defined]

    sys.modules["grok_build_bridge"] = pkg
    sys.modules["grok_build_bridge.parser"] = parser_mod
    sys.modules["grok_build_bridge.safety"] = safety_mod
    sys.modules["grok_build_bridge.deploy"] = deploy_mod
    sys.modules["grok_build_bridge.builder"] = builder_mod
    sys.modules["grok_build_bridge.xai_client"] = xai_mod
    sys.modules["grok_build_bridge._console"] = console_mod


def _install_xai_sdk_stub() -> None:
    """Ensure ``xai_sdk`` and its submodules are importable in tests.

    Real xai-sdk 1.x does **not** ship an ``errors`` submodule — rate
    limits surface as gRPC errors. The test suite still wants to
    inject scripted ``RateLimitError`` exceptions, so we always
    register a shim ``xai_sdk.errors`` module carrying a
    :class:`_StubRateLimitError`. When no real xai-sdk is installed
    (stub-only CI run) we also register ``xai_sdk`` + ``xai_sdk.tools``
    with the minimal tool factories Orchestra expects.
    """
    if "xai_sdk" not in sys.modules:
        pkg = types.ModuleType("xai_sdk")
        tools_mod = types.ModuleType("xai_sdk.tools")

        tools_mod.x_search = _stub_x_search
        tools_mod.web_search = _stub_web_search
        tools_mod.code_execution = _stub_code_execution

        pkg.RateLimitError = _StubRateLimitError  # type: ignore[attr-defined]

        sys.modules["xai_sdk"] = pkg
        sys.modules["xai_sdk.tools"] = tools_mod

    # `xai_sdk.errors` is missing from real xai-sdk 1.x — always inject
    # a shim so ``from xai_sdk.errors import RateLimitError`` works for
    # both stubbed and real-SDK test runs.
    if "xai_sdk.errors" not in sys.modules:
        errors_mod = types.ModuleType("xai_sdk.errors")
        errors_mod.RateLimitError = _StubRateLimitError
        sys.modules["xai_sdk.errors"] = errors_mod
        # Also attach as an attribute so ``import xai_sdk; xai_sdk.errors`` works.
        real_pkg = sys.modules.get("xai_sdk")
        if real_pkg is not None:
            real_pkg.errors = errors_mod  # type: ignore[attr-defined]


_install_bridge_stub()
_install_xai_sdk_stub()
