"""``ResearchPlan`` — the tree wrapper + JSON round-trip + UI snapshot.

On-disk shape (``workspace/runs/<run_id>/plan.json``):

.. code-block:: json

    {
      "schema_version": 1,
      "run_id": "abc123",
      "goal": "...",
      "config": {
        "max_depth": 3,
        "max_sub_questions_per_level": 5,
        "priority_threshold": 0.4
      },
      "created_at": "2026-04-25T12:00:00Z",
      "updated_at": "2026-04-25T12:01:00Z",
      "root": { ...SubQuestion.to_dict()... }
    }

Versioning: ``schema_version`` is bumped on any breaking change to
:class:`SubQuestion` or to the wrapper's keys. Loaders fall back
gracefully on unknown versions instead of crashing the run.
"""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from grok_orchestra.workflows.deep_research.types import (
    SubQuestion,
    SubQuestionStatus,
    _now_iso,
)

__all__ = [
    "PLAN_FILE_NAME",
    "ResearchPlan",
    "load_plan",
    "plan_path_for_run",
    "plan_tree_status",
    "save_plan",
]


PLAN_FILE_NAME = "plan.json"
SCHEMA_VERSION = 1


@dataclass
class ResearchPlan:
    """A fully-resolved research plan for one ``goal``.

    The root node's ``text`` mirrors ``goal``; every other node is a
    sub-question generated by :class:`Planner`.
    """

    goal: str
    root: SubQuestion
    run_id: str = ""
    config: Mapping[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_now_iso)
    updated_at: str = field(default_factory=_now_iso)
    schema_version: int = SCHEMA_VERSION

    # ----- shape helpers ------------------------------------------------ #

    def all_nodes(self) -> list[SubQuestion]:
        """Pre-order traversal — root first, then depth-first descendants."""
        return self.root.walk()

    def leaf_nodes(self) -> list[SubQuestion]:
        return [n for n in self.all_nodes() if n.is_leaf() and not n.is_root()]

    def find(self, node_id: str) -> SubQuestion | None:
        for n in self.all_nodes():
            if n.id == node_id:
                return n
        return None

    def progress(self) -> dict[str, int]:
        """Counts per :class:`SubQuestionStatus` — what the UI tile shows."""
        counts: dict[str, int] = {s.value: 0 for s in SubQuestionStatus}
        for n in self.all_nodes():
            counts[n.status.value] += 1
        counts["total"] = len(self.all_nodes())
        return counts

    # ----- serialization ------------------------------------------------ #

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "run_id": self.run_id,
            "goal": self.goal,
            "config": dict(self.config),
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "root": self.root.to_dict(),
        }

    @classmethod
    def from_dict(cls, raw: Mapping[str, Any]) -> ResearchPlan:
        root_raw = raw.get("root") or {}
        if not isinstance(root_raw, Mapping):
            raise ValueError("plan.json is missing 'root'")
        return cls(
            schema_version=int(raw.get("schema_version") or SCHEMA_VERSION),
            run_id=str(raw.get("run_id") or ""),
            goal=str(raw.get("goal") or ""),
            config=dict(raw.get("config") or {}),
            created_at=str(raw.get("created_at") or _now_iso()),
            updated_at=str(raw.get("updated_at") or _now_iso()),
            root=SubQuestion.from_dict(root_raw),
        )

    def touch(self) -> None:
        self.updated_at = _now_iso()


# --------------------------------------------------------------------------- #
# On-disk path resolution + I/O.
# --------------------------------------------------------------------------- #


def _workspace_root() -> Path:
    return Path(os.environ.get("GROK_ORCHESTRA_WORKSPACE") or "./workspace")


def plan_path_for_run(run_id: str) -> Path:
    return _workspace_root() / "runs" / run_id / PLAN_FILE_NAME


def save_plan(plan: ResearchPlan, path: Path | None = None) -> Path:
    """Persist ``plan`` as JSON. Returns the absolute path written."""
    if not plan.run_id and path is None:
        raise ValueError("save_plan needs either plan.run_id or an explicit path")
    target = path or plan_path_for_run(plan.run_id)
    target.parent.mkdir(parents=True, exist_ok=True)
    plan.touch()
    target.write_text(json.dumps(plan.to_dict(), indent=2), encoding="utf-8")
    return target


def load_plan(run_id: str, *, path: Path | None = None) -> ResearchPlan:
    """Read a previously-saved plan from disk.

    Raises :class:`FileNotFoundError` if no plan exists. Lets callers
    decide whether to start a fresh planning pass.
    """
    target = path or plan_path_for_run(run_id)
    if not target.exists():
        raise FileNotFoundError(f"No plan saved for run '{run_id}' at {target}")
    raw = json.loads(target.read_text(encoding="utf-8"))
    plan = ResearchPlan.from_dict(raw)
    if not plan.run_id:
        plan.run_id = run_id
    return plan


# --------------------------------------------------------------------------- #
# UI / event helpers.
# --------------------------------------------------------------------------- #


def plan_tree_status(plan: ResearchPlan) -> dict[str, Any]:
    """Compact tree dict for the dashboard — strips ``answer``/``citations``.

    The full plan can be hundreds of KB once 15b populates answers; the
    UI tree only needs structure + status icons. Callers that want the
    answers should hit ``plan.find(node_id)`` directly.
    """

    def _node(n: SubQuestion) -> dict[str, Any]:
        return {
            "id": n.id,
            "text": n.text,
            "depth": n.depth,
            "priority": round(float(n.priority), 4),
            "required_sources": [s.value for s in n.required_sources],
            "status": n.status.value,
            "children": [_node(c) for c in n.children],
        }

    return {
        "run_id": plan.run_id,
        "goal": plan.goal,
        "schema_version": plan.schema_version,
        "progress": plan.progress(),
        "root": _node(plan.root),
    }
